[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev:vite -- --host"
  targetPort = 3000
  port = 9999
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 