[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev:vite -- --host"
  targetPort = 3000
  port = 9999
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle environment variables in build
[build.environment]
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = ""
  VITE_FIREBASE_PROJECT_ID = ""
  VITE_FIREBASE_STORAGE_BUCKET = ""
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.firebaseapp.com https://*.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://* blob:; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com wss://*.firebaseio.com https://firestore.googleapis.com https://firestore.googleapis.com/google.firestore.* https://*.firestore.googleapis.com wss://*.firestore.googleapis.com; frame-src 'self' https://*.firebaseapp.com https://*.googleapis.com;" 