[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_FIREBASE_API_KEY = "AIzaSyAXrppAAu6yEMILSz8ATvb68c-k3XzIvJQ"
  VITE_FIREBASE_AUTH_DOMAIN = "my-barbershop-8c482.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "my-barbershop-8c482"
  VITE_FIREBASE_STORAGE_BUCKET = "my-barbershop-8c482.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "304927605804"
  VITE_FIREBASE_APP_ID = "1:304927605804:web:b4b226f9d27c2e34ea7d89"
  VITE_FIREBASE_MEASUREMENT_ID = "G-XY1XYTYS67"

[dev]
  framework = "#custom"
  command = "npm run dev:vite -- --host"
  targetPort = 3000
  port = 9999
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.firebaseapp.com https://*.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://* blob:; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com wss://*.firebaseio.com https://firestore.googleapis.com https://firestore.googleapis.com/google.firestore.* https://*.firestore.googleapis.com wss://*.firestore.googleapis.com; frame-src 'self' https://*.firebaseapp.com https://*.googleapis.com;" 